f=open("H:\ERAU_Year_1\Fall_Semester\CS118\GitHub2\InClassPY\myFile.txt",'w+')
f.write("***Things I love about Python***\n")
f.write("easy To learn\n")
f.write("powerful\n")
f.write("concise Code\n")
f.close()
